version: '3'
services:

    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.9
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
            - "15672:15672"

    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8000:8000"
        links:
            - rabbit

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery.sh
        volumes:
            - .:/code:Z
        links:
            - rabbit
        depends_on:
            - rabbit
